name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.3.3
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_CREDENTIALS: ${{ secrets.SSH_CREDENTIALS }}
        ARGS: "-rltgoDzvO --delete"
      with:
        local_dir: "TranSafe-Frontend/dist"
        remote_dir: "${{ fromJSON(secrets.SSH_CREDENTIALS).SSH_PATH }}"
        exclude: ".git/*"

    - name: Cleanup previous build
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_CREDENTIALS: ${{ secrets.SSH_CREDENTIALS }}
      run: |
        ssh -o StrictHostKeyChecking=no -i <(echo "$SSH_PRIVATE_KEY") ${{ fromJSON(secrets.SSH_CREDENTIALS).SSH_USER }}@${{ fromJSON(secrets.SSH_CREDENTIALS).SSH_HOST }} -p ${{ fromJSON(secrets.SSH_CREDENTIALS).SSH_PORT }} "sudo rm -rf ${{ fromJSON(secrets.SSH_CREDENTIALS).SSH_PATH }}/Render"
